diff -u --recursive --new-file linux.old/linux/MAINTAINERS linux/MAINTAINERS
--- linux.old/linux/MAINTAINERS	Wed Aug 18 23:27:15 1999
+++ linux/MAINTAINERS	Wed Aug 18 23:20:11 1999
@@ -809,6 +809,13 @@
 L:	linux-scsi@vger.rutgers.edu
 S:	Maintained
 
+UDF FILESYSTEM
+P:	Ben Fennema
+M:	bfennema@falcon.csc.calpoly.edu
+L:	linux_udf@hootie.lvld.hp.com
+W:	http://www.trylinux.com/projects/udf/index.html
+S:	Maintained
+
 UMSDOS FILESYSTEM
 P:	Matija Nalis
 M:	mnalis@jagor.srce.hr
