diff -u --recursive --new-file linux.old/Documentation/filesystems/00-INDEX linux/Documentation/filesystems/00-INDEX
--- linux.old/Documentation/filesystems/00-INDEX	Thu Sep  2 21:36:14 1999
+++ linux/Documentation/filesystems/00-INDEX	Thu Sep  2 21:33:51 1999
@@ -22,6 +22,8 @@
 	- info on using filesystems with the SMB protocol (Windows 3.11 and NT)
 sysv-fs.txt
 	- info on the SystemV/Coherent filesystem.
+udf.txt
+	- info and mount options for the UDF filesystem.
 ufs.txt
 	- info on the ufs filesystem.
 umsdos.txt
